# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:
- script: echo My first azure pipeline !
  displayName: 'Run one line script'
- script: mvn clean package
  displayName: 'Build with maven'
- script: java -jar target/Mymvnapp1-1.0-SNAPSHOT.jar
  displayName: 'Running jar'

